### PR TITLE
refs/heads/use-password-text-field Use text field

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Handles #

Changes proposed in this pull request:
- Use text field instead of text area because it has the 'secure text entry' and I don't have to implement it as a custom thing for a text view. Before was also using a hack to support a placeholder text for a text view

no error | error hidden | error visible
-------- | ------------ | ------------
passphrase-entry | error-invisible | large-error

### CODE REVIEW

**Comment by biafra23** [comment]
This is now single line and no way for the user to show, what they typed. Is this what we want?
As a user who sometimes types the seed phrase I see this as a step back.

**Comment by DmitryBespalov** [comment]
I thought it would be ok, but ok 😄 I can make a button hiding/showing the text, but this can only work with the standard single line component - the previous text area doesn't have an option to secure the entered text (iOS limitation). I will also search for a library that might do it.

**Comment by biafra23** [comment]
@DmitryBespalov Can't we use `GMTextFieldMultipleLines` ? 

Isn't this the component youre using? https://cocoapods.org/pods/GMTextField

**Comment by DmitryBespalov** [comment]
@dirk I changed the screen to make it closer to the new designs https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1551%3A16671

**Comment by biafra23** [comment]
@DmitryBespalov And there is no way to make this multiline?

**Comment by biafra23** [comment]
Also on my iPhone SE the last sentence is cut off. See screenshot.

**Comment by DmitryBespalov** [comment]
no, no way for multiline with the standard iOS controls

**Comment by DmitryBespalov** [comment]
it is cut off because there's no space for the whole content. If you click anywhere except the text field, then it will hide keyboard and you'll see whole content

**Comment by DmitryBespalov** [comment]
@biafra23 I have put a workaround to hide the keyboard when there's an error

**Comment by DmitryBespalov** [comment]
I think I found a way to have a 'secure' text with multiline

**Pull request closed without merging**
