### PR TITLE
Gh 3137 Create intro view

### PR DESCRIPTION
**Pull request by MouazAlzahabi**
Handles #3137 

Changes proposed in this pull request:
- Intro screen

### CODE REVIEW

**Comment by biafra23** [comment]
It looks like this on an iPhone SE (2020) (Same on iPhone SE 3rd gen Simulator): 
 
File (32)

**Comment by MouazAlzahabi** [comment]
@biafra23 solved already,

**Comment by biafra23** [comment]
The third rows text is still not visible.

**Review by biafra23 — APPROVED** [review]
Ok to merge, when all three lines are readable on an iPhone SE 3rd gen Simulator :-)

**Pull request merged**
