### PR TITLE
GH-3305 load safe

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Handles #3305

Changes proposed in this pull request:
- Re-configured view controllers into a UIFlow
- Added `loadSafe` route (equivalent to web's `/new-safe/load`)

### CODE REVIEW

**Comment by biafra23** [comment]
Is this just meant to be called as (for example): https://safe-wallet-web.dev.5afe.dev/new-safe/load ? Or is it possible to give parameters in the url like the address and network. So the user only needs to add a name?

The web supports at least `chain` as a parameter which preselects the chain. 

Example: https://safe-wallet-web.dev.5afe.dev/new-safe/load?chain=base

I just talked to @iamacook. Apparently the web is supposed to support `chain` and `address` and prefill the respective fields. For example: https://safe-wallet-web.dev.5afe.dev/new-safe/load?chain=eth&address=0x308686553a1EAC2fE721Ac8B814De638975a276e

**Comment by DmitryBespalov** [comment]
well, I've just tried out those links and they don't work?

**Comment by biafra23** [comment]
https://safe-wallet-web.dev.5afe.dev/new-safe/load?chain=base works for me. 
And regarding the address parameter, see: https://github.com/safe-global/safe-wallet-web/issues/2438

**Comment by DmitryBespalov** [comment]
@biafra23 I'd like to make those arguments supported in a separate pull-request. Will add this as an additional requirement.

**Review by MouazAlzahabi — APPROVED** [review]

**Review by biafra23 — APPROVED** [review]

**Pull request merged**
