### PR TITLE
Gh 865 enter seed screen

### PR DESCRIPTION
**Pull request by sche**

### CODE REVIEW

**Comment by DmitryBespalov** [comment]
@sche is this the final iteration fo this screen or more work needed on UI?
- The "Next" button is always enabled, but it should enable only when the input is valid
- The error is not showing at all
- On iPod touch the text view is covered by the keyboard and not visible at all
- Please enable the keyboard opening on the screen open automatically (`textView.becomeFirstResponder()`)

**Comment by sche** [comment]
@DmitryBespalov strange, I will take a look regarding not showing error and enables Next button. It worked fine for me.
I will enable keyboard automatically

**Comment by sche** [comment]
@DmitryBespalov I checked - it works fine for me in iPod touch. No issues with next button and displaying errors.
I decided not to use textView.becomeFirstResponder() as then user needs to scroll to read the text.

**Comment by DmitryBespalov** [comment]
@posthnikova is the keyboard should be enabled automatically when opening the seed phrase screen?

**Review by DmitryBespalov — APPROVED** [review]

**Comment by posthnikova** [comment]
@DmitryBespalov Yes, that would be nice

**Review by MouazAlzahabi — APPROVED** [review]

**Review by MouazAlzahabi — APPROVED** [review]

**Pull request merged**
