### PR TITLE
Gh 2364/secure text view

### PR DESCRIPTION
**Pull request by DmitryBespalov**
Handles #2364 

Changes proposed in this pull request:
- Add the secure text for the PK/Seed inputs

### CODE REVIEW

**Comment by biafra23** [comment]
It looks really good now with the multiline text input field. But there is a problem when deleting characters. The cursor jumps to the end. 

https://user-images.githubusercontent.com/246473/169037778-57a9b924-11a2-4f43-b315-29e2c6d44374.mov


I think the cursor position should be preserved while editing.

**Comment by DmitryBespalov** [comment]
@biafra23 thank you for catching this!

**Comment by DmitryBespalov** [comment]
should be fixed

**Comment by biafra23** [comment]
There is one small thing left. When I insert a seed phrase via password manager, it is shown, even though the eye is crossed out. When I change a thing, it switches to the dots. See video: 

https://user-images.githubusercontent.com/246473/169066991-8cda9fd6-5d12-48e7-bb46-4e2712bb0f09.mov

**Comment by DmitryBespalov** [comment]
Note to dummy self: find or create test cases for the part of the system that is changed and run through them after making the changes.

**Review by biafra23 — APPROVED** [review]

**Pull request merged**
