### PR TITLE
Rename “Get in Touch” -> “Help Center”

### PR DESCRIPTION
**Pull request by elgatovital**
Handles #1872

simulator_screenshot_461568B2-EB8F-4843-B0DD-C7AFAE82BD96
simulator_screenshot_D7595B27-CC99-4ABF-833C-B688F480C52D

### CODE REVIEW

**Review by biafra23 — APPROVED** [review]
LGTM 🚀  I only wonder, why there is no change in `project.pbxproj`. It contains the phrase in in this section:
```
		0A946D08246C4C5F00456BD5 /* Get In Touch */ = {
			isa = PBXGroup;
			children = (
				0A465C36246C2ECD00AFA467 /* GetInTouchView.swift */,
				0AD89A45246C38920052F4CD /* EmailSupportViewController.swift */,
			);
			path = "Get In Touch";
			sourceTree = "<group>";
		};
```

**Comment by elgatovital** [comment]
> LGTM 🚀 I only wonder, why there is no change in `project.pbxproj`. It contains the phrase in in this section:
> 
> ```
> 		0A946D08246C4C5F00456BD5 /* Get In Touch */ = {
> 			isa = PBXGroup;
> 			children = (
> 				0A465C36246C2ECD00AFA467 /* GetInTouchView.swift */,
> 				0AD89A45246C38920052F4CD /* EmailSupportViewController.swift */,
> 			);
> 			path = "Get In Touch";
> 			sourceTree = "<group>";
> 		};
> ```

I have not renamed GetInTouchView from SwiftUI
image

**Comment by DmitryBespalov** [comment]
@elgatovital it is the name of a folder, it's not a text of the swiftui view

**Review by DmitryBespalov — APPROVED** [review]
Let's ship it! 🚢

**Comment by elgatovital** [comment]
> @elgatovital it is the name of a folder, it's not a text of the swiftui view

that's what I said - view was not renamed

**Pull request merged**
