### PR TITLE
Gh 2593/legal disclaimer screen

### PR DESCRIPTION
**Pull request by MouazAlzahabi**
Handles #2593 

Update: 
image

### CODE REVIEW

**Comment by biafra23** [comment]
In the current design this screen has a back button. And no line between title and content.

image

**Comment by elgatovital** [comment]
is it usual to leave button floating on top of content?

**Comment by DmitryBespalov** [comment]
this screen should be shown just before choose delegate intro

**Comment by MouazAlzahabi** [comment]
> is it usual to leave button floating on top of content?

@elgatovital this is how it looks in Figma

**Comment by biafra23** [comment]
> @elgatovital this is how it looks in Figma

That is true. But we decided in your absence to change it. Maybe we need @TanyaEfremova s approval?

**Comment by biafra23** [comment]
@MouazAlzahabi It has been changed in the design as well: 
image

**Review by biafra23 — APPROVED** [review]
I think this should be correct now. I also changed the order of screens to be:

intro -> WhatIsSafe -> legal disclaimer -> Delegate

**Comment by biafra23** [comment]
@DmitryBespalov While scrolling the divider line is back :-(

image

**Pull request merged**
