### PR TITLE
Rename input to data

### PR DESCRIPTION
**Pull request by MouazAlzahabi**
Handles #2154

### CODE REVIEW

**Comment by elgatovital** [comment]
how does this fix the issue?

**Comment by biafra23** [comment]
> how does this fix the issue?

Same question from me.

**Comment by DmitryBespalov** [comment]
Mouaz, did you test on all networks?

**Comment by DmitryBespalov** [comment]
This changes fixes it because the API gives incorrect estimation when we send the "input" parameter name instead of "data" parameter name

**Review by DmitryBespalov — APPROVED** [review]

**Comment by DmitryBespalov** [comment]
Fails on Polygon: "transaction underpriced".

This is most probably because our miner fee is too low.

**Comment by DmitryBespalov** [comment]
I would close this PR for now and use it later to revisit our transaction estimation completely at another time.

**Pull request closed without merging**
