### PR TITLE
Gh 3137/select network UI

### PR DESCRIPTION
**Pull request by MouazAlzahabi**
Handles #3137 

Changes proposed in this pull request:
- Update select network view

### CODE REVIEW

**Comment by biafra23** [comment]
I am not sure if this is part of this ticket. 

But when I have already a Safe added and go to:
- Switch safe accounts
- Add safe account
- Create new Safe Account

I do not get this network selection. I get the Instructions view instead. Do we have a separate ticket for this or should it be part of this ticket?

**Comment by MouazAlzahabi** [comment]
@biafra23 I have already solved in the next pr

**Review by biafra23 — APPROVED** [review]
LGTM 🚀

**Comment by biafra23** [comment]
The Sepolia icon looks weird. I guess it is just missing. In the end these icons should come from the config service, right?

**Pull request merged**
