### PR TITLE
Gh 1655/Adjust app settings

### PR DESCRIPTION
**Pull request by elgatovital**
Handles #1655

Changes proposed in this pull request:
- Add icons for app settings items
- Adjust app settings menu
- Add separate page for terms, privacyPolicy, licenses, rateTheApp

simulator_screenshot_8C889669-26FD-45E5-96FD-0F531E4C6D53
simulator_screenshot_7DDEEDA8-B17A-41D7-A37B-D113ED3836FA

### CODE REVIEW

**Comment by lukasschor** [comment]
Why is chain prefix not part of appearance like on web?

Also thinking "Fiat currency" might be well place in appearance as well (on web there is no comparison as it's not even in setttings). But less of a strong opinion there. Definitely think fiat currency is too prominent for the fact that this is something users usually set once and then never again. :)

**Comment by biafra23** [comment]
Looks like the left margin of the `App version` is not the same as on the other cells. 

app-version-margin

Other than that it looks great, But I did not do a proper code review.

**Comment by biafra23** [comment]
@lukasschor Appearance is only about dark mode ATM. If we change this, it should be properly planned and IMHO not be part of this PR. Or even this ticket.

**Comment by elgatovital** [comment]
> Looks like the left margin of the `App version` is not the same as on the other cells.
> Other than that it looks great, But I did not do a proper code review.

Fixed: cells had different left margin

**Comment by elgatovital** [comment]
> Why is chain prefix not part of appearance like on web?
> 
> Also thinking "Fiat currency" might be well place in appearance as well (on web there is no comparison as it's not even in setttings). But less of a strong opinion there. Definitely think fiat currency is too prominent for the fact that this is something users usually set once and then never again. :)

@sche, @TanyaEfremova fresh feedback regarding app settings

**Comment by lukasschor** [comment]
> @lukasschor Appearance is only about dark mode ATM. If we change this, it should be properly planned and IMHO not be part of this PR. Or even this ticket.

Yes didn't mean this should be changed in this PR/ticket, just wanted to share an opinion based on the screenshot. Next time I'll provide the feedback on slack instead.

**Comment by TanyaEfremova** [comment]
@lukasschor Agreed, a few items in the app settings should be grouped logically, but as @biafra23 said, it is not yet a part of this ticket, but it's a part of another task that is in backlog for now.

**Review by biafra23 — APPROVED** [review]
Meinen Segen hast Du :-) 👍🏻

**Review by DmitryBespalov — APPROVED** [review]

**Pull request merged**
