### PR TITLE
Fix CLA url

### PR DESCRIPTION
**Pull request by elgatovital**

### CODE REVIEW

**Comment by MouazAlzahabi** [comment]
What does this one solve exactly? do we have reported issue ?

**Comment by elgatovital** [comment]
> What does this one solve exactly? do we have reported issue ?

the cla url was wrong.

**Comment by MouazAlzahabi** [comment]
Then please make a ticket for it and connect it so it could be testable by QA

**Comment by elgatovital** [comment]
> Then please make a ticket for it and connect it so it could be testable by QA

how would you like qa to test it? Just copy the old link into your browser, see that it doesn't work. Do the same with the new link to see that it works and approve the pr. No need to complicate the matter so much.

**Review by MouazAlzahabi — APPROVED** [review]

**Comment by MouazAlzahabi** [comment]
Sorry I just misunderstood the intention of this change, thought it's related to something else

**Pull request merged**
