### PR TITLE
Rename input to from

### PR DESCRIPTION
**Pull request by MouazAlzahabi**
Handles #3301 

Changes proposed in this pull request:
- After comparing to the request sent by our web interface, I did this change, by doing so I get exactly the same estimated gas of both interfaces, and estimation still works on all networks

### CODE REVIEW

**Comment by DmitryBespalov** [comment]
Glad that you found how to  fix this! Did you test that the execution still works?

**Comment by MouazAlzahabi** [comment]
Yes I created safe on the zkSync Era

**Comment by DmitryBespalov** [comment]
ok, I meant if it still works on such chain as gnosis chain, polygon, and goerli

**Comment by MouazAlzahabi** [comment]
I tried safe creation on Goerli, Polygon and zkSync and all working fine

**Review by DmitryBespalov — APPROVED** [review]

**Pull request merged**
